[package]
name = "dxe-types"
version = "0.1.0"
edition = "2024"

[features]
sql = ["sqlx"]

[dependencies]
sqlx = { version = "0.8", features = [
    "derive",
    "runtime-tokio",
], optional = true }
