[package]
name = "dxe-extern"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { workspace = true }
gcp_auth = "0.12"
parking_lot = { workspace = true }
reqwest = { workspace = true, features = ["multipart", "stream"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }
